[package]
name = "lilufo"
version = "0.1.0"
authors = ["Eli Heuer <elih@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

norad = "0.1.0"
clap = "2.33.0"
